# Generated by Django 3.1.3 on 2022-01-05 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0003_auto_20220105_2347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cifarimage',
            old_name='cifarImg',
            new_name='Image',
        ),
        migrations.RenameField(
            model_name='mnistimage',
            old_name='mnistImg',
            new_name='Image',
        ),
    ]
