# Generated by Django 3.1.3 on 2022-02-22 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0004_auto_20220105_2348'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CifarImage',
        ),
    ]
