# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fileTransfer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='fileTransfer.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12\x66ileTransfer.proto\"\x84\x01\n\rServerMessage\x12%\n\rdownloadOrder\x18\x01 \x01(\x0b\x32\x0e.DownloadOrder\x12!\n\x0buploadOrder\x18\x02 \x01(\x0b\x32\x0c.UploadOrder\x12)\n\x0f\x64isconnectOrder\x18\x03 \x01(\x0b\x32\x10.DisconnectOrder\"\x81\x01\n\rClientMessage\x12\x39\n\x17\x64ownloadAcknowledgement\x18\x01 \x01(\x0b\x32\x18.DownloadAcknowledgement\x12\x35\n\x15uploadAcknowledgement\x18\x02 \x01(\x0b\x32\x16.UploadAcknowledgement\"<\n\rDownloadOrder\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12\x0f\n\x07ifTrain\x18\x03 \x01(\x05\"\'\n\x17\x44ownloadAcknowledgement\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"\x1b\n\x0bUploadOrder\x12\x0c\n\x04name\x18\x01 \x01(\t\"3\n\x15UploadAcknowledgement\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"\x11\n\x0f\x44isconnectOrder2A\n\x0c\x46ileTransfer\x12\x31\n\x0bOpenChannel\x12\x0e.ClientMessage\x1a\x0e.ServerMessage(\x01\x30\x01\x62\x06proto3'
)




_SERVERMESSAGE = _descriptor.Descriptor(
  name='ServerMessage',
  full_name='ServerMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='downloadOrder', full_name='ServerMessage.downloadOrder', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='uploadOrder', full_name='ServerMessage.uploadOrder', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='disconnectOrder', full_name='ServerMessage.disconnectOrder', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=155,
)


_CLIENTMESSAGE = _descriptor.Descriptor(
  name='ClientMessage',
  full_name='ClientMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='downloadAcknowledgement', full_name='ClientMessage.downloadAcknowledgement', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='uploadAcknowledgement', full_name='ClientMessage.uploadAcknowledgement', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=158,
  serialized_end=287,
)


_DOWNLOADORDER = _descriptor.Descriptor(
  name='DownloadOrder',
  full_name='DownloadOrder',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='DownloadOrder.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='DownloadOrder.data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ifTrain', full_name='DownloadOrder.ifTrain', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=289,
  serialized_end=349,
)


_DOWNLOADACKNOWLEDGEMENT = _descriptor.Descriptor(
  name='DownloadAcknowledgement',
  full_name='DownloadAcknowledgement',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='DownloadAcknowledgement.data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=351,
  serialized_end=390,
)


_UPLOADORDER = _descriptor.Descriptor(
  name='UploadOrder',
  full_name='UploadOrder',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='UploadOrder.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=392,
  serialized_end=419,
)


_UPLOADACKNOWLEDGEMENT = _descriptor.Descriptor(
  name='UploadAcknowledgement',
  full_name='UploadAcknowledgement',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='UploadAcknowledgement.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='UploadAcknowledgement.data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=421,
  serialized_end=472,
)


_DISCONNECTORDER = _descriptor.Descriptor(
  name='DisconnectOrder',
  full_name='DisconnectOrder',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=474,
  serialized_end=491,
)

_SERVERMESSAGE.fields_by_name['downloadOrder'].message_type = _DOWNLOADORDER
_SERVERMESSAGE.fields_by_name['uploadOrder'].message_type = _UPLOADORDER
_SERVERMESSAGE.fields_by_name['disconnectOrder'].message_type = _DISCONNECTORDER
_CLIENTMESSAGE.fields_by_name['downloadAcknowledgement'].message_type = _DOWNLOADACKNOWLEDGEMENT
_CLIENTMESSAGE.fields_by_name['uploadAcknowledgement'].message_type = _UPLOADACKNOWLEDGEMENT
DESCRIPTOR.message_types_by_name['ServerMessage'] = _SERVERMESSAGE
DESCRIPTOR.message_types_by_name['ClientMessage'] = _CLIENTMESSAGE
DESCRIPTOR.message_types_by_name['DownloadOrder'] = _DOWNLOADORDER
DESCRIPTOR.message_types_by_name['DownloadAcknowledgement'] = _DOWNLOADACKNOWLEDGEMENT
DESCRIPTOR.message_types_by_name['UploadOrder'] = _UPLOADORDER
DESCRIPTOR.message_types_by_name['UploadAcknowledgement'] = _UPLOADACKNOWLEDGEMENT
DESCRIPTOR.message_types_by_name['DisconnectOrder'] = _DISCONNECTORDER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ServerMessage = _reflection.GeneratedProtocolMessageType('ServerMessage', (_message.Message,), {
  'DESCRIPTOR' : _SERVERMESSAGE,
  '__module__' : 'fileTransfer_pb2'
  # @@protoc_insertion_point(class_scope:ServerMessage)
  })
_sym_db.RegisterMessage(ServerMessage)

ClientMessage = _reflection.GeneratedProtocolMessageType('ClientMessage', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTMESSAGE,
  '__module__' : 'fileTransfer_pb2'
  # @@protoc_insertion_point(class_scope:ClientMessage)
  })
_sym_db.RegisterMessage(ClientMessage)

DownloadOrder = _reflection.GeneratedProtocolMessageType('DownloadOrder', (_message.Message,), {
  'DESCRIPTOR' : _DOWNLOADORDER,
  '__module__' : 'fileTransfer_pb2'
  # @@protoc_insertion_point(class_scope:DownloadOrder)
  })
_sym_db.RegisterMessage(DownloadOrder)

DownloadAcknowledgement = _reflection.GeneratedProtocolMessageType('DownloadAcknowledgement', (_message.Message,), {
  'DESCRIPTOR' : _DOWNLOADACKNOWLEDGEMENT,
  '__module__' : 'fileTransfer_pb2'
  # @@protoc_insertion_point(class_scope:DownloadAcknowledgement)
  })
_sym_db.RegisterMessage(DownloadAcknowledgement)

UploadOrder = _reflection.GeneratedProtocolMessageType('UploadOrder', (_message.Message,), {
  'DESCRIPTOR' : _UPLOADORDER,
  '__module__' : 'fileTransfer_pb2'
  # @@protoc_insertion_point(class_scope:UploadOrder)
  })
_sym_db.RegisterMessage(UploadOrder)

UploadAcknowledgement = _reflection.GeneratedProtocolMessageType('UploadAcknowledgement', (_message.Message,), {
  'DESCRIPTOR' : _UPLOADACKNOWLEDGEMENT,
  '__module__' : 'fileTransfer_pb2'
  # @@protoc_insertion_point(class_scope:UploadAcknowledgement)
  })
_sym_db.RegisterMessage(UploadAcknowledgement)

DisconnectOrder = _reflection.GeneratedProtocolMessageType('DisconnectOrder', (_message.Message,), {
  'DESCRIPTOR' : _DISCONNECTORDER,
  '__module__' : 'fileTransfer_pb2'
  # @@protoc_insertion_point(class_scope:DisconnectOrder)
  })
_sym_db.RegisterMessage(DisconnectOrder)



_FILETRANSFER = _descriptor.ServiceDescriptor(
  name='FileTransfer',
  full_name='FileTransfer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=493,
  serialized_end=558,
  methods=[
  _descriptor.MethodDescriptor(
    name='OpenChannel',
    full_name='FileTransfer.OpenChannel',
    index=0,
    containing_service=None,
    input_type=_CLIENTMESSAGE,
    output_type=_SERVERMESSAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_FILETRANSFER)

DESCRIPTOR.services_by_name['FileTransfer'] = _FILETRANSFER

# @@protoc_insertion_point(module_scope)
