# Generated by Django 3.1.3 on 2022-01-05 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cifar',
            new_name='CifarImage',
        ),
        migrations.RenameModel(
            old_name='Mnist',
            new_name='MnistImage',
        ),
    ]
