# Generated by Django 3.1.3 on 2022-01-05 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0002_auto_20220105_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cifarimage',
            name='name',
        ),
        migrations.RemoveField(
            model_name='mnistimage',
            name='name',
        ),
    ]
